name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin 
    - name: Run code coverage
      run: cargo tarpaulin --ignore-tests
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Format code
      run: cargo fmt -- --check
    - name: Install audit
      run: cargo install cargo-audit
    - name: Run audit
      run: cargo audit
